---
title: "Assignment 7"
author: "Zofia Sikorska"
format: html
editor: visual
---

## Importing libraries

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("tidyverse")

```

```{r}
library(tidyr)
library(dplyr)
library(readr)
```

## Transforming data set to longer one

```{r}
iris_long <- iris %>%
  pivot_longer(cols = !Species, names_to = "Trait", values_to = "Size")

head(iris_long)
```

## Mean lenght and width of sepal and petal

```{r}
iris_means <- iris_long %>%
  group_by(Species, Trait) %>%
  summarize(Mean=mean(Size)) 
View(iris_means)
iris_means
```

## Largest and widest petal and sepal

```{r}
iris_max <- iris_long %>%
  filter(Species %in% c("virginica", "versicolor")) %>%
  group_by(Species, Trait) %>%
  summarize(Max = max(Size)) 

View(iris_max)
iris_max
```

## Observations above mean

```{r}
above_mean <- iris_long %>%
  # joining long with mean table and checking which values are bigger than mean
  left_join(iris_means, by = c("Species", "Trait")) %>%
  mutate(Above_mean = Size > Mean) %>%
  
  #grouping and counting values
  group_by(Species, Trait)%>%
  summarize(Above_mean = sum(Above_mean))

View(above_mean)
above_mean
```
